/**
 * Provider-agnostic payment abstraction. PaymentService talks only to this
 * interface — no Stripe-specific types or calls appear outside
 * stripe-payment-provider.ts, so adding Razorpay (or any other provider)
 * later means writing one new file that implements this interface, not
 * touching booking/payment business logic.
 */
export interface CreatePaymentIntentParams {
  /** Decimal string, e.g. "5000.00" — the provider implementation is
   * responsible for converting to whatever unit it requires. */
  amount: string;
  currency: string;
  metadata: { bookingId: string; userId: string };
}

export interface PaymentIntentResult {
  providerPaymentId: string;
  /** Opaque value the frontend needs to complete payment client-side
   * (Stripe's PaymentIntent client_secret). Never a secret credential. */
  clientSecret: string;
}

export interface ProviderWebhookEvent {
  /** The provider's own id for this specific event delivery — used for
   * audit trails, not as the primary idempotency mechanism (see the
   * Payment.providerEventId schema comment for why). */
  id: string;
  type: string;
  providerPaymentId: string;
  amount: string;
  currency: string;
  /** Present only for refund-related event types; empty string otherwise
   * (matching how irrelevant payment events already report empty fields —
   * see stripe-payment-provider.ts). */
  providerRefundId: string;
  /** The refund's own status as reported by this event ("pending" |
   * "succeeded" | "failed"); empty string when not a refund event. */
  refundStatus: string;
}

export interface CreateRefundParams {
  providerPaymentId: string;
  amount: string;
  currency: string;
  /** Generated by us before ever calling the provider (see Refund.idempotencyKey)
   * and passed through as the provider's own idempotency key — a retried
   * call with the same key resolves to the same provider-side refund
   * instead of moving money twice. */
  idempotencyKey: string;
}

export interface RefundResult {
  providerRefundId: string;
  status: "pending" | "succeeded" | "failed";
}

export interface PaymentProvider {
  readonly name: string;
  createPaymentIntent(params: CreatePaymentIntentParams): Promise<PaymentIntentResult>;
  retrievePaymentIntent(providerPaymentId: string): Promise<PaymentIntentResult>;
  createRefund(params: CreateRefundParams): Promise<RefundResult>;
  /** Re-checks a refund already created at the provider — used when a
   * previous attempt got a providerRefundId back but crashed before we
   * recorded its final status, so a retry never calls createRefund twice
   * for the same logical attempt. */
  retrieveRefund(providerRefundId: string): Promise<RefundResult>;
  /** Verifies the signature and parses the event. Must throw if the
   * signature is invalid — never trust an unverified payload. */
  verifyWebhookSignature(rawBody: Buffer, signature: string): ProviderWebhookEvent;
}
